// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTJE5DNr9xCxTSnwZ110OZUJfRqzV6_YM',
    appId: '1:335374614123:android:64632b011672428bf27b2e',
    messagingSenderId: '335374614123',
    projectId: 'flutterproject-ebcc4',
    storageBucket: 'flutterproject-ebcc4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQwM9Uddg9K70VjqSves5fDni0ujakvvg',
    appId: '1:335374614123:ios:0ac8b9fc9531bfc7f27b2e',
    messagingSenderId: '335374614123',
    projectId: 'flutterproject-ebcc4',
    storageBucket: 'flutterproject-ebcc4.appspot.com',
    iosClientId: '335374614123-prpivdvkqkecigkb6p3mrts6gjn56fsj.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterStatemanagement',
  );
}
